matrix:
  PYTHON_VERSION:
    - miniconda2
    - miniconda3

pipeline:
  build:
    image: kszucs/${PYTHON_VERSION}
    commands:
      - python setup.py test

  pypi:
    repository: https://pypi.python.org/pypi
    username: $$PYPI_USERNAME
    password: $$PYPI_PASSWORD
    distributions:
      - sdist
      - bdist_wheel
    when:
      event: [tag]
