- repo: https://github.com/pre-commit/pre-commit-hooks.git
  sha: HEAD
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-docstring-first
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: detect-aws-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: flake8
    args: ['--config=setup.cfg']
    exclude: __init__.py
  - id: pretty-format-json
  - id: requirements-txt-fixer
  - id: double-quote-string-fixer
  - id: trailing-whitespace
  - id: debug-statements
  - id: autopep8-wrapper
